-- Owner-visible time clock actions for the AuditLog trail.
ALTER TYPE "AuditAction" ADD VALUE 'TIME_CLOCK_ENABLED';
ALTER TYPE "AuditAction" ADD VALUE 'TIME_CLOCK_DISABLED';
ALTER TYPE "AuditAction" ADD VALUE 'TIME_CLOCK_OVERTIME_RULES_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'TIME_CLOCK_ACCESS_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'TIME_CLOCK_ENTRY_CORRECTED';
